root: true

extends:
  - plugin:@mysticatea/es2015
  - plugin:@mysticatea/+modules
  - plugin:@mysticatea/+node

rules:
  "@mysticatea/node/no-unsupported-features/es-syntax":
    - error
    - ignores:
      - modules
