sudo: false

language: node_js
node_js:
  - 6.5.0
  - 8
  - 10

script:
  - npm test

after_success:
  - npm run -s codecov

before_deploy:
  - npm run -s docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ATOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master
    node: 10
